import {
  ARIEL_WA_CONTENT,
  BATTLE_GROUND_CONTENT,
  BRUSH_PRAIRIE_CONTENT,
  GRESHAM_CONTENT,
  HAPPY_VALLEY_CONTENT,
  KALAMA_CONTENT,
  KELSO_CONTENT,
  NORTH_BONNEVILLE_CONTENT,
  OREGON_SERVICES_CONTENT,
  PORTLAND_CONTENT,
  RIDGEFIELD_CONTENT,
  TROUTDALE_CONTENT,
  VANCOUVER_CONTENT,
  WASHINGTON_SERVICES_CONTENT,
  WASHOUGAL_CONTENT,
  WOODLAND_CONTENT,
  YACOLT_CONTENT,
} from "@/data/cities/cities";

export const CITIES_PAGES = {
  ariel: ARIEL_WA_CONTENT,
  "battle-ground": BATTLE_GROUND_CONTENT,
  "brush-prairie": BRUSH_PRAIRIE_CONTENT,
  kalama: KALAMA_CONTENT,
  kelso: KELSO_CONTENT,
  "north-bonneville": NORTH_BONNEVILLE_CONTENT,
  ridgefiield: RIDGEFIELD_CONTENT,
  vancouver: VANCOUVER_CONTENT,
  washougal: WASHOUGAL_CONTENT,
  woodland: WOODLAND_CONTENT,
  yacolt: YACOLT_CONTENT,
  portland: PORTLAND_CONTENT,
  "happy-valley": HAPPY_VALLEY_CONTENT,
  gresham: GRESHAM_CONTENT,
  troutdale: TROUTDALE_CONTENT,
};

export const STATES_PAGES = {
  washington: WASHINGTON_SERVICES_CONTENT,
  oregon: OREGON_SERVICES_CONTENT,
};
